### ISSUE TITLE
OSS License?

### ISSUE THREAD

**Issue by douglasryanadams** [mohsenk/janus-java-sdk#3]
Hello, is it possible to clarify what license this software falls under? We'd like to consider it but are unclear what license applies.

Would you have a problem with applying an MIT license? I'd be happy to open up a PR if that helps.

**Comment by mohsenk** [comment]
Hello,
Yes. sure.  I will do it.

Thanks for your collaboration.

**Comment by douglasryanadams** [comment]
Awesome thank you!
